version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/MWC_project
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    # logging:
    #   driver: "json-file"
      # options:
      #   max-size: "10m"
      #   max-file: "3"

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    # logging:
    #   driver: "json-file"
      # options:
      #   max-size: "10m"
      #   max-file: "3"

volumes:
  mongo_data:
    driver: local
